RUN mkdir -p /usr/bin
COPY stages/arch/blikvm_source/package/kvmd-fan/kvmd-fan.py /usr/bin/kvmd-fan
RUN chmod 755 /usr/bin/kvmd-fan

RUN mkdir -p /usr/lib/systemd/system
COPY stages/arch/blikvm_source/package/kvmd-fan/kvmd-fan.service /usr/lib/systemd/system/kvmd-fan.service

COPY stages/arch/blikvm/override.yaml /etc/kvmd/override.yaml

COPY stages/arch/blikvm/tc358743-edid.hex /etc/kvmd/tc358743-edid.hex

RUN sed -i -e "s|dtoverlay=tc358743|dtoverlay=tc358743,4lane=1|g" /boot/config.txt
